spring.application.name=backend

app.repository.type=SQL
spring.datasource.url=jdbc:postgresql://localhost:15432/shiftconnect-db
spring.datasource.username=shiftconnect-db-user
spring.datasource.password=shiftconnect-db-pwd

spring.jpa.hibernate.ddl-auto=update