spring.application.name=backend

app.repository.type=SQL
spring.datasource.url=jdbc:postgresql://localhost:15432/shiftconnect-db
spring.datasource.username=shiftconnect-db-user
spring.datasource.password=shiftconnect-db-pwd

spring.jpa.hibernate.ddl-auto=update

# TODO: Store the secret in a secure way, not in the properties file (.env is not working for this)
jwt.secret=0lhf5cCT/TS5gmeNLCqqKS1NEjbV08NByg0s2LNHuCw=
jwt.issuer=shiftconnect-backend
jwt.audience=shiftconnect-frontend
jwt.access-token-minutes=60
